import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F8FAFC', padding: 16 },
  title: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  subtitle: { fontSize: 12, color: '#64748B', marginTop: 2 },
  overline: { marginTop: 12, fontSize: 12, color: '#64748B' },
  grid3: { flexDirection: 'row', gap: 12, marginTop: 8 },
  grid2: { flexDirection: 'row', gap: 12, marginTop: 8 },
  fuelCard: { flex: 1, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EDF0', borderRadius: 16, padding: 12, alignItems: 'center', justifyContent: 'center' },
  fuelCardActive: { borderColor: '#14617B', backgroundColor: 'rgba(20,97,123,0.05)' },
  fuelLabel: { marginTop: 4, fontSize: 12, color: '#64748B' },
  fuelPrice: { marginTop: 2, fontSize: 14, fontWeight: '700', color: '#0F172A' },
  input: { marginTop: 8, borderWidth: 1, borderColor: '#E6EDF0', borderRadius: 14, paddingHorizontal: 12, height: 44, backgroundColor: '#FFFFFF', color: '#0F172A' },
  quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  pill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, borderWidth: 1, borderColor: '#E6EDF0', backgroundColor: '#FFFFFF' },
  pillActive: { backgroundColor: '#14617B', borderColor: '#14617B' },
  pillText: { fontSize: 12, color: '#0F172A' },
  pillTextActive: { color: '#FFFFFF', fontWeight: '700' },
  card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 12, marginTop: 12, borderWidth: 1, borderColor: '#E6EDF0' },
  cardTitle: { fontSize: 14, fontWeight: '600', color: '#0F172A' },
  cardSub: { marginTop: 4, fontSize: 12, color: '#64748B' },
  link: { marginTop: 6, color: '#14617B', fontSize: 12, fontWeight: '600' },
  iconBadge: { height: 28, width: 28, borderRadius: 8, backgroundColor: '#ECFDF5', alignItems: 'center', justifyContent: 'center' },
  totalCard: { marginTop: 12, borderRadius: 12, padding: 12 },
  totalOverline: { fontSize: 12, color: '#065F46' },
  totalValue: { fontSize: 22, fontWeight: '700', color: '#065F46', marginTop: 2 },
  totalIcon: { height: 40, width: 40, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' },
  cta: { marginTop: 16, backgroundColor: '#10B981', borderRadius: 16, height: 48, alignItems: 'center', justifyContent: 'center' },
  ctaText: { color: '#F7FBFE', fontSize: 16, fontWeight: '600' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 },
  muted: { color: '#64748B' },
  value: { color: '#0F172A' },
  applyButton: { height: 36, borderRadius: 10, paddingHorizontal: 8, minWidth: 60, backgroundColor: '#14617B', alignItems: 'center', justifyContent: 'center' },
  applyButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },
  vehiclePill: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E6EDF0', backgroundColor: '#FFFFFF', borderRadius: 16, padding: 10, marginRight: 10 },
  vehiclePillActive: { borderColor: '#14617B', backgroundColor: 'rgba(20,97,123,0.05)' },
  vehicleThumb: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#EEE' },
  vehicleTitle: { fontSize: 13, fontWeight: '700', color: '#0F172A' },
  vehicleSub: { fontSize: 11, color: '#64748B' },
  addVehicleBox: { width: 56, height: 56, borderRadius: 14, borderWidth: 1, borderColor: '#E6EDF0', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  dispatcherCard: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E6EDF0', borderRadius: 16, padding: 12, backgroundColor: '#FFFFFF' },
  dispatcherCardActive: { borderColor: '#14617B', backgroundColor: 'rgba(20,97,123,0.05)' },
  dispatcherTitle: { fontWeight: '700', color: '#0F172A' },
  dispatcherSub: { fontSize: 12, color: '#64748B' },
});
