import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.light.subtleBg, padding: 16 },
  title: { fontSize: 18, fontWeight: '700', color: Colors.light.text },
  subtitle: { fontSize: 12, color: Colors.light.muted, marginTop: 2 },
  overline: { marginTop: 12, fontSize: 12, color: Colors.light.muted },
  grid3: { flexDirection: 'row', gap: 12, marginTop: 8 },
  grid2: { flexDirection: 'row', gap: 12, marginTop: 8 },
  fuelCard: { flex: 1, backgroundColor: Colors.light.background, borderWidth: 1, borderColor: Colors.light.cardBorder, borderRadius: 16, padding: 12, alignItems: 'center', justifyContent: 'center' },
  fuelCardActive: { borderColor: Colors.light.tint, backgroundColor: 'rgba(185,28,28,0.05)' },
  fuelLabel: { marginTop: 4, fontSize: 12, color: Colors.light.muted },
  fuelPrice: { marginTop: 2, fontSize: 14, fontWeight: '700', color: Colors.light.text },
  input: { marginTop: 8, borderWidth: 1, borderColor: Colors.light.cardBorder, borderRadius: 14, paddingHorizontal: 12, height: 44, backgroundColor: Colors.light.background, color: Colors.light.text },
  quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  pill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, borderWidth: 1, borderColor: Colors.light.cardBorder, backgroundColor: Colors.light.background },
  pillActive: { backgroundColor: Colors.light.tint, borderColor: Colors.light.tint },
  pillText: { fontSize: 12, color: Colors.light.text },
  pillTextActive: { color: Colors.light.background, fontWeight: '700' },
  card: { backgroundColor: Colors.light.background, borderRadius: 16, padding: 12, marginTop: 12, borderWidth: 1, borderColor: Colors.light.cardBorder },
  cardTitle: { fontSize: 14, fontWeight: '600', color: Colors.light.text },
  cardSub: { marginTop: 4, fontSize: 12, color: Colors.light.muted },
  link: { marginTop: 6, color: Colors.light.tint, fontSize: 12, fontWeight: '600' },
  iconBadge: { height: 28, width: 28, borderRadius: 8, backgroundColor: Colors.light.background, alignItems: 'center', justifyContent: 'center' },
  totalCard: { marginTop: 12, borderRadius: 12, padding: 12 },
  totalOverline: { fontSize: 12, color: Colors.light.tint },
  totalValue: { fontSize: 22, fontWeight: '700', color: Colors.light.tint, marginTop: 2 },
  totalIcon: { height: 40, width: 40, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' },
  cta: { marginTop: 16, backgroundColor: Colors.light.tint, borderRadius: 16, height: 48, alignItems: 'center', justifyContent: 'center' },
  ctaText: { color: Colors.light.background, fontSize: 16, fontWeight: '600' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 },
  muted: { color: Colors.light.muted },
  value: { color: Colors.light.text },
  applyButton: { height: 36, borderRadius: 10, paddingHorizontal: 8, minWidth: 60, backgroundColor: Colors.light.tint, alignItems: 'center', justifyContent: 'center' },
  applyButtonText: { color: Colors.light.background, fontWeight: '700', fontSize: 12 },
  vehiclePill: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Colors.light.cardBorder, backgroundColor: Colors.light.background, borderRadius: 16, padding: 10, marginRight: 10 },
  vehiclePillActive: { borderColor: Colors.light.tint, backgroundColor: 'rgba(185,28,28,0.05)' },
  vehicleThumb: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#EEE' },
  vehicleTitle: { fontSize: 13, fontWeight: '700', color: Colors.light.text },
  vehicleSub: { fontSize: 11, color: Colors.light.muted },
  addVehicleBox: { width: 56, height: 56, borderRadius: 14, borderWidth: 1, borderColor: Colors.light.cardBorder, backgroundColor: Colors.light.background, alignItems: 'center', justifyContent: 'center' },
  dispatcherCard: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Colors.light.cardBorder, borderRadius: 16, padding: 12, backgroundColor: Colors.light.background },
  dispatcherCardActive: { borderColor: Colors.light.tint, backgroundColor: 'rgba(185,28,28,0.05)' },
  dispatcherTitle: { fontWeight: '700', color: Colors.light.text },
  dispatcherSub: { fontSize: 12, color: Colors.light.muted },
});
